### ISSUE TITLE
Build error -> missing OBJ folder -> OBJFace.cs and OBJFile.cs

### ISSUE THREAD

**Issue by lingme** [LoL-Fantome/LeagueToolkit#104]
Project missing OBJFace and OBJFile class, I checked the commit record, was found in the 
**0b942b4b0e0613b24c9adcc39674592dce54d3c6**
the commit was removed, but the commit message is to modify the project name, after I manually add these two classes, compile successfully, accidentally delete?

**Comment by Crauzer** [comment]
Fixed 20cd29b1738326682b3ba1f1f16226802e7c729f

**Comment by lingme** [comment]
Quick fix as always
