### ISSUE TITLE
Property bin version 3 isn't supported

### ISSUE THREAD

**Issue by Jochem-W** [LoL-Fantome/LeagueToolkit#106]
A lot of skins have switched to using version 3 property bins, which cannot be read by LeagueToolkit. While I have no idea how to properly reverse engineer binary files, it seems like the general structure is still the same since the new files can be read just fine if I change the version number back to 2 in a hex editor.

Here's a sample property bin version 3 file [Pantheon.wad.client.zip](https://github.com/LoL-Fantome/LeagueToolkit/files/5783631/Pantheon.wad.client.zip).

**Comment by Crauzer** [comment]
Fixed
