### ISSUE TITLE
Setter in PropertyBin 

### ISSUE THREAD

**Issue by Rerago** [LoL-Fantome/LeagueToolkit#109]
Hi,

I want to edit a PropertyBin to change some settings. Unfortunately the setters for e.g. BinTreeBool are set to Private. So I have to remove the property and add it with a changed value. This changes the order unnecessarily.

Is there any particular reason for this? Or am I missing something?

**Comment by Crauzer** [comment]
Thanks for reporting, this is indeed not intended, I'll change the access modifiers for Values to public
