### ISSUE TITLE
DX11 Mode is not supported on Mapgeo

### ISSUE THREAD

**Issue by TheKillerey** [LoL-Fantome/LeagueToolkit#113]
![image](https://user-images.githubusercontent.com/18242778/128593463-de8bef90-ac68-4589-b73b-c926545dba8a.png)
It only works on DX9 Legacy mode.

**Comment by Morilli** [comment]
Will probably need some more info here. Any idea what is causing this? Or have a working / not working .mapgeo comparison?

**Comment by TheKillerey** [comment]
I think it's something related to the meshes imported to the mapgeo. Because on my halloween map or old rift map I had some working meshes in the past. I need to test them again if I am correct.

**Comment by TheKillerey** [comment]
So Old Summoners Rift worked using dx11 mode which confuses me somehow. So I think it's the way how models are loaded into the mapgeo format.
