### ISSUE TITLE
Nuget-Update

### ISSUE THREAD

**Issue by Rerago** [LoL-Fantome/LeagueToolkit#116]
Hi, could you please possibly update the nuget package accordingly? It still points to 2.4.2

**Comment by Morilli** [comment]
I would if I could, but the `LeagueToolkit` package on nuget can only be updated by @Crauzer currently, who is no longer actively maintaining this project.

**Comment by Rerago** [comment]
Is he then online from time to time and could give you rights there? Because to copy the project over to your own projects would be more of a step backwards.

Btw. are you open for PRs? E.g. We could update the nuget-packages in the project (e.g. ZstdSharp 0.7.1 is used although there is 0.7.2). We could also check if "https://github.com/oleg-st/ZstdSharp" would be something for the project, since this repro is still actively worked on.

And this is something I would also like to tackle again:

https://github.com/LoL-Fantome/LeagueToolkit/pull/112

**Comment by Rerago** [comment]
@Morilli If we have no way to reach him to change this. Shall we choose another name if necessary? Because I would not like to copy the whole project to use it in my project.

**Comment by Morilli** [comment]
I have reached out to him but not received an answer yet. For now, you should be able to use a git submodule (assuming you're using git) which should provide a relatively clean way to use this project without handling manual copying and updating.

I'd say wait a bit more, otherwise I will look for an alternative; I don't quite feel comfortable publishing as a fork or whatever yet.

**Comment by Rerago** [comment]
Ok the git submodule worked great. I can work with it for now. But I think we leave the issue open for now.

**Comment by Rerago** [comment]
I have seen there were some commits by @Crauzer. But unfortunately there was no nuget update yet. Is there anything else that needs to be done for the CI or would it just need to run the task? @Morilli

**Comment by Rerago** [comment]
it happened :)

https://www.nuget.org/packages/LeagueToolkit/
