### ISSUE TITLE
Metaclasses json

### ISSUE THREAD

**Issue by Rerago** [LoL-Fantome/LeagueToolkit#135]
I wanted to replace `Newtonsoft.Json` with `System.Text.Json`. But to test the whole thing I need this `meta_11.8.370.4668.json` or the one from the current patch. Where can I download it?

**Comment by Morilli** [comment]
You can find  those jsons here: https://github.com/moonshadow565/league-meta-jsons/tree/master/live-meta

**Comment by Rerago** [comment]
Ok this is strange. I loaded exactly the "meta_11.8.370.4668.json" but the code in the sandbox does not work. It breaks already directly at the deserialize. So I can not check if my conversion would work :/

**Comment by Morilli** [comment]
It broke in 75fe0eb7ef0cca7e84b72e2d027ca09be6647e18. May be worth trying to figure out why the `List` -> `Dictionary` change was made and apparently worked at the time.

**Comment by Rerago** [comment]
I suspect that he is using a different JSON as a base. Because the version before [75fe0eb](https://github.com/LoL-Fantome/LeagueToolkit/commit/75fe0eb7ef0cca7e84b72e2d027ca09be6647e18) is exactly the JSON you linked. The current code must have worked with a different JSON.

**Comment by moonshadow565** [comment]
Its changed to new format from here: https://github.com/LoL-Fantome/LeagueMetaJson

**Comment by Rerago** [comment]
Question was answered then and the issue should have been closed then, sorry.
