### ISSUE TITLE
Error: Out of range when importing models to MAPGEO

### ISSUE THREAD

**Issue by TheKillerey** [LoL-Fantome/LeagueToolkit#150]
![image](https://user-images.githubusercontent.com/18242778/164131372-242764d2-ee62-4c0c-8ddb-32cb23e67d2b.png)
Error appears on my PROJECT Rift Map. I can't import all or 200 meshes otherwise it will get out of range. If I import 100 it exports as normal. Complete model sizes are 77,8 MB. 1KB min. to 1.148KB max. I can fix this issue myself but I want to inform you about that.

**Comment by Morilli** [comment]
Could you provide a stacktrace or the specific line the error is coming from? It's hard to figure out without having the workflow setup to test this myself.

**Comment by TheKillerey** [comment]
Sure the line comes when I write my mapgeo file

Moritz Bender ***@***.***> schrieb am Mi., 20. Apr. 2022,
05:04:

**Comment by Crauzer** [comment]
Send the stacktrace

**Comment by TheKillerey** [comment]
Hey, I was not home yet to share anything:
[bugmapgeo.txt](https://github.com/LoL-Fantome/LeagueToolkit/files/8523526/bugmapgeo.txt)
I am not sure if it was the correct one because I never did that before. But I saw something with 
GenerateVertexElementGroups.
![image](https://user-images.githubusercontent.com/18242778/164282656-d07a7c99-9c17-456d-bc64-64929970f2fc.png)

**Comment by TheKillerey** [comment]
![image](https://user-images.githubusercontent.com/18242778/164283123-6a2fd37f-9a9c-4863-9e20-ca84324ff392.png)

**Comment by Crauzer** [comment]
that's exactly the same function I sent, that'd mean one of your models contains 0 vertices, because it's tryong to access the first one

**Comment by TheKillerey** [comment]
I will add then a rule if the model has 0 vertices. It makes no sense to me because all of my models have vertices.
