### ISSUE TITLE
[SimpleSkin] Support for vertex of size 72

### ISSUE THREAD

**Issue by Crauzer** [LoL-Fantome/LeagueToolkit#163]
base Akali.skn

**Comment by Morilli** [comment]
See for example https://github.com/CommunityDragon/CDTB/pull/67

**Comment by Crauzer** [comment]
This new vertex type is used for League's [BSDF ubershader](https://docs.blender.org/manual/en/latest/render/shader_nodes/shader/principled.html)

**Comment by Crauzer** [comment]
fixed by #166
