### ISSUE TITLE
Allow passing in raw texture data instead of `SixLabors.ImageSharp.Image` in `SimpleSkinGltfExtensions.ToGltf`

### ISSUE THREAD

**Issue by Morilli** [LoL-Fantome/LeagueToolkit#198]
In the `SimpleSkinGltfExtensions.ToGltf` function, it would be favourable to be able to provide raw texture data (in `byte[]` form or similar) instead of having it be a `SixLabors.ImageSharp.Image` parameter.

This would get rid of the `SixLabors.Imagesharp` dependency (it is not used anymore else in this project) and should work without issues, as decoding and reencoding the image is not necessary for gltf; the `SharpGLTF.Memory.MemoryImage` constructors takes raw `byte[]` data anyways.

This also solves the current issue in the lol2gltf project where material textures are most prominently in the dds format, which ImageSharp doesn't support by default without an additional package that isn't on nuget yet.

**Comment by Crauzer** [comment]
GLTF by itself doesn't support DDS textures without a schema extension which the `SharpGltf` library doesn't support to my knowledge. We will have to use the [BCnEncoder](https://github.com/Nominom/BCnEncoder.NET) library to decode the textures into PNG images in order to be able to store them into GLTF.

**Comment by Morilli** [comment]
SharpGLTF *does* support the `MSFT_texture_dds` extension, see https://github.com/vpenades/SharpGLTF/blob/master/src/SharpGLTF.Core/README.md

**Comment by Crauzer** [comment]
Thanks for finding that! I couldn't seem to find that on my phone. In that case we just need to check if it works as intended and we can change the API into something more modern.

**Comment by Morilli** [comment]
I do have a local version of lol2gltf that appears to work fine with the necessary changes, however when trying to verify the correctness I was not able to find a single glTF viewer that actually supports the `MSFT_texture_dds` extension. Given that, it's probably better to actually convert the file data to png format to make sure people can actually use the resulting file.
