### ISSUE TITLE
[Nuget] Release frequency or pre-release versions

### ISSUE THREAD

**Issue by Rerago** [LoL-Fantome/LeagueToolkit#204]
Between [2.4.2](https://www.nuget.org/packages/LeagueToolkit/2.4.2) and [3.0.2](https://www.nuget.org/packages/LeagueToolkit/3.0.2) was roughly 1 1/2 years.

Is there a rough plan on how to proceed with the versions? Or would [prerelease-packages](https://learn.microsoft.com/de-de/nuget/create-packages/prerelease-packages) be something to think about? So one could make a prerelease e.g. with each PR (that would be possibly frequently) or in certain time intervals). So you could do a prerelease e.g. with every PR (that would possibly be a bit frequent) or in certain time intervals.

I would like to use the change from #188, but I don't know when a new release is coming. Means the only possibility for me would be back to [git submodule](https://git-scm.com/book/de/v2/Git-Tools-Submodule) which is kinda not so cool.

**Comment by Crauzer** [comment]
I will publish a v4.0.0 pre-release soon. I will most likely keep publishing pre-release versions until I stabilize a larger part of the API.

**Comment by Crauzer** [comment]
https://github.com/LoL-Fantome/LeagueToolkit/releases/tag/4.0.0-beta.1

**Comment by Rerago** [comment]
Works perfectly. Thank you.
