### ISSUE TITLE
Missing field names in many bin files

### ISSUE THREAD

**Issue by Rerago** [LoL-Fantome/LeagueToolkit#208]
Not really a `LeagueToolkit` issue but I don`t know where else exactly to put this. (maybe we can use [discussions](https://github.com/LoL-Fantome/LeagueToolkit/discussions))

I have unpacked the wads with [Obsidian](https://github.com/Crauzer/Obsidian) and wanted to look at them with [Scavenger](https://github.com/Crauzer/Scavenger). But I noticed that many names are not known. So I took the source code and included the newest [Meta](https://www.nuget.org/packages/LeagueToolkit.Meta.Classes/12.23.485.7490). Unfortunately this helped me only conditionally. A lot of properties just don't have a name. These values seem to come from the `FIELDS_HASHTABLE.txt` (or, [hashes.binfields.txt](https://github.com/CommunityDragon/CDTB/blob/master/cdragontoolbox/hashes.binfields.txt)). Unfortunately this file is already 2 months old.

Is there anything I can do?

PS: 

Only reference to `LeagueToolkit` would be the questions if we could update `LeagueToolkit.Meta.Classes` to the v13 patch? :)

**Comment by Crauzer** [comment]
We use hashes provided by the people over at [CDragon](https://github.com/CommunityDragon/CDTB).
If I recall correctly, they have an automated system for generating hashes on each league update with various different methods, but of course there are still quite a bit of unknown ones in most areas.

> Only reference to LeagueToolkit would be the questions if we could update LeagueToolkit.Meta.Classes to the v13 patch? :)

Yup

**Comment by Rerago** [comment]
Then I close that times.

I hope that there is soon an update. Because currently I can not fix my tool :/

**Comment by Crauzer** [comment]
I'll probably push an update tonight

**Comment by Crauzer** [comment]
https://github.com/LoL-Fantome/LeagueToolkit/pull/211
